version: "3.9"

services:
  web:
    build: ./backend
    container_name: rail_web
    command: gunicorn liverailtracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      PYTHONPATH: /app  # <-- add this


  celery:
    build: ./backend
    container_name: rail_celery
    command: celery -A liverailtracker worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      PYTHONPATH: /app

  celery_beat:
    build: ./backend
    container_name: rail_celery_beat
    command: celery -A liverailtracker beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      PYTHONPATH: /app

  redis:
    image: redis:latest
    container_name: rail_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: rail_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
